
dist: trusty
addons:
  apt:
    packages:
    - couchdb




language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "1.8"
  - "2.5"
  - "3.3"
  - "4.9"
  - "5.12"
  - "6.14"
  - "7.10"
env:
  global:
  - COUCHDB_PORT=5984

services:
  - couchdb